safe: true
base-url: /
post_dirs: false
destination: ../_site

plugins: ./_plugins

markdown: maruku
permalink: pretty

timezone: America/New_York
lsi: true

# prose options
prose:
  rooturl: "_posts"
  siteurl: "http://dh.chadblack.net"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "author"
        field:
          element: "text"
          label: "author"
          placeholder: "your name"
          value: ""
          
    

